Repository Team-Motivoo/Motivoo-Android, pull requests merged in 2024-03, with the labels that each got.

#103 [feat] 네트워크 연결 상태 확인 (로딩,에러 뷰)
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/motivoo/data/datasource/remote/intercepter/AuthInterceptor.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/intercepter/ErrorInterceptor.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/listener/AuthTokenRefreshListener.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/listener/AuthTokenRefreshListenerImpl.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/listener/NetworkErrorListener.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/listener/NetworkErrorListenerImpl.kt
  app/src/main/java/sopt/motivoo/data/repository/NetworkRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/di/CoroutineModule.kt
  app/src/main/java/sopt/motivoo/di/Logger.kt
  app/src/main/java/sopt/motivoo/di/NetworkModule.kt
  app/src/main/java/sopt/motivoo/di/RepositoryModule.kt
  app/src/main/java/sopt/motivoo/di/RetrofitModule.kt
  app/src/main/java/sopt/motivoo/domain/repository/NetworkRepository.kt
  app/src/main/java/sopt/motivoo/presentation/LoadingFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/MainViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/NetworkErrorFragment.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/auth/AuthViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewHolder.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/intro/StartMotivooFragment.kt
  app/src/main/java/sopt/motivoo/presentation/invitecode/GetInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/loading/LoadingFragment.kt
  app/src/main/java/sopt/motivoo/presentation/my_exercise_info/MyExerciseInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyLogoutFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyPageFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyServiceOutFragment.kt
  app/src/main/java/sopt/motivoo/util/FindStartDestination.kt
  app/src/main/java/sopt/motivoo/util/NetworkState.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/res/layout/fragment_connection_error.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 준희 👻

#104 [feat] 로그아웃, 회원탈퇴시 새 액티비티 띄우기
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/intro/PermissionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/my_exercise_info/MyExerciseInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyLogoutFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyServiceOutFragment.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
Labels: feat, Pull Request :fire:, 준희 👻

#119 [refactor/feat] 홈 뷰 로직 수정 및 개선 & AlarmManager 기능 구현
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/motivoo/data/datasource/local/StepCountLocalDataSource.kt
  app/src/main/java/sopt/motivoo/data/repository/FirebaseRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/data/repository/StepCountRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/di/DispatcherModule.kt
  app/src/main/java/sopt/motivoo/di/Logger.kt
  app/src/main/java/sopt/motivoo/domain/repository/FirebaseRepository.kt
  app/src/main/java/sopt/motivoo/domain/repository/StepCountRepository.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeState.kt
  app/src/main/java/sopt/motivoo/presentation/home/broadcastreceiver/BootCompletedReceiver.kt
  app/src/main/java/sopt/motivoo/presentation/home/broadcastreceiver/HomeAlarmReceiver.kt
  app/src/main/java/sopt/motivoo/presentation/home/service/StepCountService.kt
  app/src/main/java/sopt/motivoo/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
Labels: feat, 관희 🐪 , refactoring

#121 [fix] #120 Android 12 하위 버전 AlarmManager 대응
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/broadcastreceiver/HomeAlarmReceiver.kt
  app/src/main/java/sopt/motivoo/presentation/home/service/StepCountService.kt
Labels: fix, Pull Request :fire:, 관희 🐪 

#122 [feat] #109 412 HTTP 에러 코드 핸들링
  app/src/main/java/sopt/motivoo/data/error/UserErrorHandlerImpl.kt
  app/src/main/java/sopt/motivoo/data/model/response/home/ResponseMissionChoiceDto.kt
  app/src/main/java/sopt/motivoo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/di/RepositoryModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/error/ResponseHandler.kt
  app/src/main/java/sopt/motivoo/domain/entity/home/MissionChoiceData.kt
  app/src/main/java/sopt/motivoo/domain/error/UserErrorHandler.kt
  app/src/main/java/sopt/motivoo/domain/repository/HomeRepository.kt
  app/src/main/java/sopt/motivoo/presentation/home/viewmodel/HomeViewModel.kt
Labels: feat, 관희 🐪 

#123 [add] 컬러 추가
  app/src/main/res/values/colors.xml
  motivoo_design/src/main/res/values/colors.xml
Labels: add, Pull Request :fire:, 준희 👻

#126 [add] 오픈소스 라이선스 추가
  app/build.gradle
  app/src/main/java/sopt/motivoo/presentation/mypage/MyPageFragment.kt
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: add, Pull Request :fire:, 준희 👻

#131 [UI] 홈 UI 변경
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_home_mission_complete.xml
  app/src/main/res/drawable/ic_home_mission_uncomplete.xml
  app/src/main/res/drawable/ic_unconnection.xml
  app/src/main/res/drawable/img_home.png
  app/src/main/res/drawable/img_home_mission_complete.png
  app/src/main/res/layout/activity_sample.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/navigation_main.xml
  motivoo_design/src/main/java/com/android/motivoo_design/MotivooOtherPieChart.kt
  motivoo_design/src/main/res/drawable/ic_child_user.xml
  motivoo_design/src/main/res/drawable/ic_parent_user.xml
  motivoo_design/src/main/res/layout/motivoo_mission_card.xml
  motivoo_design/src/main/res/values/attrs.xml
Labels: UI, Pull Request :fire:, 관희 🐪 

#133 [feat] Firebase 권한 규칙 수정
  app/build.gradle
  app/src/main/ic_motivoo-playstore.png
  app/src/main/java/sopt/motivoo/data/repository/FirebaseRepositoryImpl.kt
  app/src/main/res/drawable/ic_motivoo_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_motivoo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_motivoo_round.xml
  app/src/main/res/mipmap-hdpi/ic_motivoo.webp
  app/src/main/res/mipmap-hdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-mdpi/ic_motivoo.webp
  app/src/main/res/mipmap-mdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_motivoo.webp
  app/src/main/res/mipmap-xhdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_motivoo.webp
  app/src/main/res/mipmap-xxhdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_motivoo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_motivoo_round.webp
  app/src/main/res/values/ic_motivoo_background.xml
Labels: Pull Request :fire:, 관희 🐪 

#124 [feat] 마이페이지 2차 스프린트 내용 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/sopt/motivoo/presentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_shoes.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 현지 🐱
