Repository Team-Motivoo/Motivoo-Android, pull requests merged in 2024-04, with the labels that each got.

#136 [QA] 홈 뷰 QA 1차
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/service/StepCountService.kt
  app/src/main/java/sopt/motivoo/presentation/home/viewmodel/HomeViewModel.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/res/drawable/ic_clap_sound.xml
  app/src/main/res/layout/bottom_sheet_home.xml
  app/src/main/res/layout/dialog_home_photo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request :fire:, 관희 🐪 , QA

#140 [QA] 운동 뷰 QA 1차 수정
  app/build.gradle
  app/src/main/java/sopt/motivoo/data/model/response/ResponseExerciseDto.kt
  app/src/main/java/sopt/motivoo/domain/entity/exercise/ExerciseData.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseAdapter.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewHolder.kt
  app/src/main/res/drawable/background_exercise.xml
  app/src/main/res/drawable/ic_bubble_exercising.xml
  app/src/main/res/drawable/img_exercise_today_shoes.xml
  app/src/main/res/drawable/shape_rectangle_white_radius6.xml
  app/src/main/res/layout/bottom_sheet_home.xml
  app/src/main/res/layout/dialog_home_photo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item_exercise.xml
  app/src/main/res/layout/item_exercise_today.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 현지 🐱, QA

#142 [Feat] 비트맵 리사이징
  app/src/main/java/sopt/motivoo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/presentation/home/bottomsheet/HomeBottomSheetFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/dialog/HomePhotoDialogFragment.kt
  app/src/main/java/sopt/motivoo/util/BitmapRequestBody.kt
  app/src/main/java/sopt/motivoo/util/BitmapUtil.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
Labels: feat, Pull Request :fire:, 관희 🐪 , refactoring

#144 Qa/#143 home v2
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/ic_home_mission_uncomplete.xml
  app/src/main/res/drawable/img_home_mission_uncomplete.png
  app/src/main/res/layout/bottom_sheet_home.xml
  app/src/main/res/layout/dialog_home_photo.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_sore_spot_qusetion.xml
  app/src/main/res/values/colors.xml
  motivoo_design/src/main/res/layout/motivoo_step_count_text.xml
Labels: Pull Request :fire:, 관희 🐪 
