Repository Team-Motivoo/Motivoo-Android, pull requests merged in 2024-01, with the labels that each got.

#2 [Init] 프로젝트 초기세팅
  .editorconfig
  .gitignore
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/ktlint.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/sopt/motivoo/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/motivoo/MainActivity.kt
  app/src/main/java/sopt/motivoo/MotivooApplication.kt
  app/src/main/java/sopt/motivoo/data/datasource/local/MotivooStorageImpl.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/DummyDataSource.kt
  app/src/main/java/sopt/motivoo/data/model/request/DummyRequestData.kt
  app/src/main/java/sopt/motivoo/data/model/response/DummyResponseData.kt
  app/src/main/java/sopt/motivoo/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/data/service/DummyService.kt
  app/src/main/java/sopt/motivoo/di/Logger.kt
  app/src/main/java/sopt/motivoo/di/RepositoryModule.kt
  app/src/main/java/sopt/motivoo/di/RetrofitModule.kt
  app/src/main/java/sopt/motivoo/di/ServiceModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/MotivooStorage.kt
  app/src/main/java/sopt/motivoo/domain/entity/dummy/DummyInfoList.kt
  app/src/main/java/sopt/motivoo/domain/repository/DummyRepository.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/dummy/DummyActivity.kt
  app/src/main/java/sopt/motivoo/presentation/dummy/DummyViewModel.kt
  app/src/main/java/sopt/motivoo/util/ContentUriRequestBody.kt
  app/src/main/java/sopt/motivoo/util/Event.kt
  app/src/main/java/sopt/motivoo/util/EventObserver.kt
  app/src/main/java/sopt/motivoo/util/UiState.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingActivity.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingAdapter.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingBottomSheetDialogFragment.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingFragment.kt
  app/src/main/java/sopt/motivoo/util/extension/ActivityExt.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/java/sopt/motivoo/util/extension/ItemDiffCallback.kt
  app/src/main/java/sopt/motivoo/util/extension/MediatorLiveDataExt.kt
  app/src/main/java/sopt/motivoo/util/extension/ParcelableExt.kt
  app/src/main/java/sopt/motivoo/util/extension/ViewExt.kt
  app/src/main/res/layout/activity_dummy.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/sopt/motivoo/ExampleUnitTest.kt
  build.gradle
Labels: Pull Request :fire:, 준희 👻, init

#4 [feat] jetpack navigation 구현
  app/build.gradle
  app/src/main/java/sopt/motivoo/presentation/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/LoginFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/dummy/DummyActivity.kt
  app/src/main/java/sopt/motivoo/presentation/dummy/DummyFragment.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingActivity.kt
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_dummy.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/navigation/navigation_main.xml
  build.gradle
Labels: feat, Pull Request :fire:, 준희 👻

#6 [feat] webview 세팅
  app/build.gradle
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/WebViewFragment.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/layout/fragment_webview.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: feat, Pull Request :fire:, 준희 👻

#10 [add] typography 추가
  app/src/main/res/font-v26/pretendard.xml
  app/src/main/res/font/pretendard.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/values/text_appearance.xml
Labels: add, Pull Request :fire:, 준희 👻

#12 [add] 컬러 리소스 추가
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: add, Pull Request :fire:, 현지 🐱

#17 [ui] 커스텀 원형 그래프 제작 🔨
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooStepCountText.kt
  app/src/main/java/sopt/motivoo/util/extension/FontExt.kt
  app/src/main/res/layout/motivoo_step_count_text.xml
  app/src/main/res/values/attrs.xml
Labels: feat, UI, Pull Request :fire:, 관희 🐪 

#16 [feat] splash 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/res/drawable/ic_motivoo_logo.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat, UI, Pull Request :fire:, 준희 👻

#22 [ui] 홈 화면 초안 (미션 선택 전)
  app/src/main/java/sopt/motivoo/presentation/HomeFragment.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooMissionCard.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooPieChart.kt
  app/src/main/res/drawable/background_mission_card.xml
  app/src/main/res/drawable/ic_clap_sound.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/motivoo_mission_card.xml
  app/src/main/res/layout/motivoo_step_count_text.xml
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request :fire:, 관희 🐪 

#23 [UI] 온보딩 뷰 작업
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/sopt/motivoo/presentation/LoginFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/AgeQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/DoExerciseQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/FrequencyQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/GetInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/SoreSpotQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/TimeQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/WhatActivityQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/WhatExerciseQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/type/DoExerciseType.kt
  app/src/main/java/sopt/motivoo/presentation/type/FrequencyType.kt
  app/src/main/java/sopt/motivoo/presentation/type/SoreSpotType.kt
  app/src/main/java/sopt/motivoo/presentation/type/TimeType.kt
  app/src/main/java/sopt/motivoo/presentation/type/UserType.kt
  app/src/main/java/sopt/motivoo/presentation/type/WhatActivityType.kt
  app/src/main/java/sopt/motivoo/presentation/type/WhatExerciseType.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingAdapter.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/java/sopt/motivoo/util/extension/ViewExt.kt
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/anim/slide_out_right.xml
  app/src/main/res/drawable/bg_edittext_error.xml
  app/src/main/res/drawable/selector_edittext_input.xml
  app/src/main/res/drawable/selector_next_button_background.xml
  app/src/main/res/drawable/selector_onboarding_button_background.xml
  app/src/main/res/drawable/selector_text_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_age_qusetion.xml
  app/src/main/res/layout/fragment_do_exercise_question.xml
  app/src/main/res/layout/fragment_frequency_qusetion.xml
  app/src/main/res/layout/fragment_get_invite_code.xml
  app/src/main/res/layout/fragment_sore_spot_qusetion.xml
  app/src/main/res/layout/fragment_time_qusetion.xml
  app/src/main/res/layout/fragment_what_activity_question.xml
  app/src/main/res/layout/fragment_what_exercise_qusetion.xml
  app/src/main/res/layout/view_do_exercise_button.xml
  app/src/main/res/layout/view_frequency_button.xml
  app/src/main/res/layout/view_onboarding_toolbar.xml
  app/src/main/res/layout/view_sore_spot_button.xml
  app/src/main/res/layout/view_time_button.xml
  app/src/main/res/layout/view_user_type_button.xml
  app/src/main/res/layout/view_what_activity_button.xml
  app/src/main/res/layout/view_what_exercise_button.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request :fire:, 준희 👻

#26 [UI] 마이페이지 마이, 마이_내정보 뷰 제작
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/MyInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ripple_gray200_rectangle.xml
  app/src/main/res/drawable/ripple_gray200_rectangle_bottom_radius8.xml
  app/src/main/res/drawable/ripple_gray200_rectangle_radius30.xml
  app/src/main/res/drawable/ripple_gray200_rectangle_radius8.xml
  app/src/main/res/drawable/shape_rectangle_bottom_radius8.xml
  app/src/main/res/drawable/shape_rectangle_top_radius8.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_myinfo.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: UI, add, Pull Request :fire:, 현지 🐱

#29 [feat] 마이_운동정보 뷰 제작
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/MyExerciseInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_exercise_info.xml
  app/src/main/res/layout/fragment_mypage_myinfo.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: feat, UI, add, Pull Request :fire:, 현지 🐱

#32 [ui] 초대코드 뷰작업
  app/src/main/java/sopt/motivoo/presentation/invitecode/GetInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/invitecode/InviteCodeViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/invitecode/PostInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/login/AfterLoginFragment.kt
  app/src/main/java/sopt/motivoo/presentation/login/LoginFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/AgeQuestionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/GetInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/drawable/selector_text_color.xml
  app/src/main/res/drawable/shape_edittext_error_radius8.xml
  app/src/main/res/drawable/shape_get_invite_code_copy_button_radius8.xml
  app/src/main/res/drawable/shape_get_invite_code_radius8.xml
  app/src/main/res/layout/fragment_after_login.xml
  app/src/main/res/layout/fragment_age_qusetion.xml
  app/src/main/res/layout/fragment_do_exercise_question.xml
  app/src/main/res/layout/fragment_frequency_qusetion.xml
  app/src/main/res/layout/fragment_get_invite_code.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_post_invite_code.xml
  app/src/main/res/layout/fragment_sore_spot_qusetion.xml
  app/src/main/res/layout/fragment_time_qusetion.xml
  app/src/main/res/layout/fragment_what_activity_question.xml
  app/src/main/res/layout/fragment_what_exercise_qusetion.xml
  app/src/main/res/layout/motivoo_step_count_text.xml
  app/src/main/res/layout/view_custom_toast.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
Labels: UI, Pull Request :fire:, 준희 👻

#19 [feat] 앱 진입 시 접근 권한 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/intro/PermissionFragment.kt
  app/src/main/java/sopt/motivoo/presentation/login/LoginFragment.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_caution.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_health.xml
  app/src/main/res/drawable/selector_button_background.xml
  app/src/main/res/layout/fragment_permission.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: feat, UI, Pull Request :fire:, 준희 👻

#34 [feat] dialog 제작
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/MyExerciseInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyLogoutFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyServiceOutFragment.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingDialogFragment.kt
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_shoes.xml
  app/src/main/res/drawable/shape_rectangle_radius8.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_exercise_info.xml
  app/src/main/res/layout/fragment_mypage_logout.xml
  app/src/main/res/layout/fragment_mypage_myinfo.xml
  app/src/main/res/layout/fragment_mypage_service_out.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: feat, UI, add, Pull Request :fire:, 현지 🐱

#35 [ui] 최종 홈 UI 구현
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooMyPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooOtherPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooStepCountText.kt
  app/src/main/res/drawable/bg_mission_card.xml
  app/src/main/res/drawable/ic_child_other.xml
  app/src/main/res/drawable/ic_child_user.xml
  app/src/main/res/drawable/ic_parent_other.xml
  app/src/main/res/drawable/ic_parent_user.xml
  app/src/main/res/drawable/ic_question.xml
  app/src/main/res/drawable/img_step_count.png
  app/src/main/res/drawable/selector_home_verify_exercise.xml
  app/src/main/res/drawable/selector_home_verify_exercise_text.xml
  app/src/main/res/drawable/shape_rectangle_radius_8_solid_gray100.xml
  app/src/main/res/drawable/shape_rectangle_radius_8_solid_gray900.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/motivoo_mission_card.xml
  app/src/main/res/layout/motivoo_step_count_text.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request :fire:, 관희 🐪 

#40 [feat/ui] 홈 바텀 시트 & 인증 모달 & 카메라 기능 & 앨범 기능
  app/src/main/java/sopt/motivoo/presentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeConfirmDialogFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomePhotoDialogFragment.kt
  app/src/main/java/sopt/motivoo/util/binding/BindingDialogFragment.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/res/drawable/background_bottom_sheet.xml
  app/src/main/res/drawable/background_mission_card.xml
  app/src/main/res/drawable/ic_album.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/shape_rectangle_radius_8_solid_white.xml
  app/src/main/res/layout/bottom_sheet_home.xml
  app/src/main/res/layout/dialog_home_cofirm.xml
  app/src/main/res/layout/dialog_home_photo.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/motivoo_mission_card.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, UI, Pull Request :fire:, 관희 🐪 

#41 [feat] exercise view 제작 및 기능 구현
  .idea/git_toolbox_prj.xml
  app/build.gradle
  app/src/main/java/sopt/motivoo/domain/entity/ExerciseInfo.kt
  app/src/main/java/sopt/motivoo/presentation/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseAdapter.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewHolder.kt
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/img_exercise_fake.png
  app/src/main/res/drawable/img_notexercise.xml
  app/src/main/res/drawable/img_thumb.xml
  app/src/main/res/drawable/img_unconnection.xml
  app/src/main/res/drawable/shape_rectangle_gray50_radius8.xml
  app/src/main/res/drawable/shape_rectangle_radius24.xml
  app/src/main/res/layout/fragment_connection_error.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_logout.xml
  app/src/main/res/layout/fragment_mypage_service_out.xml
  app/src/main/res/layout/item_exercise.xml
  app/src/main/res/layout/item_exercise_notice.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/raw/lodinglottie.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, UI, Pull Request :fire:, 현지 🐱

#46 [feat] 로딩중 뷰 구현
  app/src/main/java/sopt/motivoo/presentation/LoadingFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/res/layout/fragment_loading.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/raw/loading_animation_lottie.json
  app/src/main/res/raw/lodinglottie.json
Labels: feat, UI, Pull Request :fire:, 현지 🐱

#60 [ui] 터치영역 수정
  app/src/main/java/sopt/motivoo/presentation/intro/TermsOfUseFragment.kt
  app/src/main/res/layout/fragment_terms_of_use.xml
  app/src/main/res/values/strings.xml
Labels: UI, Pull Request :fire:, 준희 👻

#52 [feat] 웹뷰 fragment 연결
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 현지 🐱

#66 [feat] 홈 뷰 중간 작업
  app/build.gradle
  app/src/main/java/sopt/motivoo/data/datasource/local/MotivooStorageImpl.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/AuthInterceptor.kt
  app/src/main/java/sopt/motivoo/data/datasource/remote/HomeDataSource.kt
  app/src/main/java/sopt/motivoo/data/model/request/home/RequestHomeDto.kt
  app/src/main/java/sopt/motivoo/data/model/request/home/RequestMissionImageDto.kt
  app/src/main/java/sopt/motivoo/data/model/request/home/RequestMissionTodayDto.kt
  app/src/main/java/sopt/motivoo/data/model/response/home/ResponseHomeDto.kt
  app/src/main/java/sopt/motivoo/data/model/response/home/ResponseMissionChoiceDto.kt
  app/src/main/java/sopt/motivoo/data/model/response/home/ResponseMissionImageDto.kt
  app/src/main/java/sopt/motivoo/data/model/response/home/ResponseMissionTodayDto.kt
  app/src/main/java/sopt/motivoo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/data/service/HomeService.kt
  app/src/main/java/sopt/motivoo/di/FirebaseModule.kt
  app/src/main/java/sopt/motivoo/di/RepositoryModule.kt
  app/src/main/java/sopt/motivoo/di/RetrofitModule.kt
  app/src/main/java/sopt/motivoo/di/ServiceModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/MotivooStorage.kt
  app/src/main/java/sopt/motivoo/domain/entity/home/HomeData.kt
  app/src/main/java/sopt/motivoo/domain/entity/home/MissionChoiceData.kt
  app/src/main/java/sopt/motivoo/domain/entity/home/MissionChoiceListData.kt
  app/src/main/java/sopt/motivoo/domain/entity/home/MissionImageData.kt
  app/src/main/java/sopt/motivoo/domain/entity/home/TodayMissionData.kt
  app/src/main/java/sopt/motivoo/domain/repository/HomeRepository.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeBottomSheetFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeConfirmDialogFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomePhotoDialogFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/home/StepCountService.kt
  app/src/main/java/sopt/motivoo/util/Constants.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooDeniedPermission.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooMissionCard.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooMyPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooOtherPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooStepCountText.kt
  app/src/main/java/sopt/motivoo/util/extension/ContextExt.kt
  app/src/main/res/drawable/ic_clap_sound.xml
  app/src/main/res/drawable/img_home.png
  app/src/main/res/drawable/img_home_mission_complete.png
  app/src/main/res/drawable/img_step_count.png
  app/src/main/res/layout/dialog_home_cofirm.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/motivoo_denied_permission.xml
  app/src/main/res/layout/motivoo_mission_card.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 관희 🐪 

#63 [mod] #62 뒤로가기 로직 개선 및 SharedPreferences 값 초기화
  app/src/main/java/sopt/motivoo/data/datasource/local/MotivooStorageImpl.kt
  app/src/main/java/sopt/motivoo/di/RetrofitModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/MotivooStorage.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/auth/AuthViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/invitecode/GetInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/raw/splash_view_lottie.json
Labels: chore, Pull Request :fire:, 준희 👻

#68 [mod] 로그아웃 & 회원탈퇴 다이어로그
  app/src/main/java/sopt/motivoo/presentation/MyLogoutFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyServiceOutFragment.kt
  app/src/main/res/layout/fragment_mypage_logout.xml
  app/src/main/res/layout/fragment_mypage_service_out.xml
Labels: chore, Pull Request :fire:, 관희 🐪 

#70 [QA] 권한 분기처리 추가
  app/src/main/java/sopt/motivoo/presentation/intro/PermissionFragment.kt
  app/src/main/res/navigation/navigation_main.xml
Labels: Pull Request :fire:, 준희 👻, QA

#49 [feat] 마이 뷰 서버 연결
  app/src/main/java/sopt/motivoo/data/service/MyPageService.kt
  app/src/main/java/sopt/motivoo/di/ServiceModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/ResponseMyPageDto.kt
  app/src/main/java/sopt/motivoo/domain/entity/mypage/UserInfo.kt
  app/src/main/java/sopt/motivoo/domain/repository/MyPageRepository.kt
  app/src/main/java/sopt/motivoo/presentation/MyInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyPageViewModel.kt
  app/src/main/res/navigation/navigation_main.xml
Labels: feat, Pull Request :fire:, 현지 🐱

#61 [feat] 운동 정보 조회 서버 연결
  app/src/main/java/sopt/motivoo/data/model/response/ResponseMyExerciseInfoDto.kt
  app/src/main/java/sopt/motivoo/data/service/MyExerciseInfoService.kt
  app/src/main/java/sopt/motivoo/di/ServiceModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/MyExerciseInfo.kt
  app/src/main/java/sopt/motivoo/presentation/MyExerciseInfoFragment.kt
  app/src/main/java/sopt/motivoo/presentation/my_exercise_info/MyExerciseInfoViewModel.kt
  app/src/main/res/layout/fragment_mypage_exercise_info.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 현지 🐱

#72 [QA] 권한 분기처리 로직 수정
  app/src/main/java/sopt/motivoo/data/datasource/local/MotivooStorageImpl.kt
  app/src/main/java/sopt/motivoo/domain/entity/MotivooStorage.kt
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/intro/PermissionFragment.kt
  app/src/main/res/navigation/navigation_main.xml
Labels: chore, Pull Request :fire:, 준희 👻

#73 [qa] 권한 분기처리 마지막 수정
  app/src/main/java/sopt/motivoo/presentation/SplashFragment.kt
  app/src/main/java/sopt/motivoo/presentation/intro/PermissionFragment.kt
Labels: chore, Pull Request :fire:, 준희 👻

#56 [feat] 운동 뷰 서버 연결 중간 Merge PR
  app/build.gradle
  app/src/main/java/sopt/motivoo/data/model/response/ResponseExerciseDto.kt
  app/src/main/java/sopt/motivoo/data/model/response/ResponseMyPageDto.kt
  app/src/main/java/sopt/motivoo/data/service/ExerciseService.kt
  app/src/main/java/sopt/motivoo/data/service/MyPageService.kt
  app/src/main/java/sopt/motivoo/di/ServiceModule.kt
  app/src/main/java/sopt/motivoo/domain/entity/ExerciseInfo.kt
  app/src/main/java/sopt/motivoo/domain/entity/ResponseMyPageDto.kt
  app/src/main/java/sopt/motivoo/domain/entity/exercise/ExerciseData.kt
  app/src/main/java/sopt/motivoo/domain/repository/MyPageRepository.kt
  app/src/main/java/sopt/motivoo/presentation/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseAdapter.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewHolder.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewModel.kt
  app/src/main/java/sopt/motivoo/util/extension/LocalDate.kt
  app/src/main/res/drawable/ic_thumb_up.xml
  app/src/main/res/layout/item_exercise.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: feat, 현지 🐱, 준서 👾

#78 [feat] 바텀 네비게이션 뷰 재선택 이벤트 제거
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
Labels: feat, QA

#81 Feat/#80 modify bottom navigation font
  app/src/main/res/drawable/selector_bottomnavi_text_color.xml
  app/src/main/res/layout/activity_main.xml
Labels: UI, QA

#82 [QA] 기디 qa 반영
  app/src/main/java/sopt/motivoo/data/datasource/local/MotivooStorageImpl.kt
  app/src/main/java/sopt/motivoo/data/model/response/ResponseMyPageDto.kt
  app/src/main/java/sopt/motivoo/presentation/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/java/sopt/motivoo/presentation/auth/LoginFragment.kt
  app/src/main/java/sopt/motivoo/presentation/exercise/ExerciseViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/invitecode/GetInviteCodeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_age_qusetion.xml
  app/src/main/res/layout/fragment_exercise.xml
  app/src/main/res/layout/fragment_get_invite_code.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_logout.xml
  app/src/main/res/layout/fragment_mypage_service_out.xml
  app/src/main/res/layout/fragment_permission.xml
  app/src/main/res/layout/fragment_post_invite_code.xml
  app/src/main/res/layout/fragment_sore_spot_qusetion.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/layout/fragment_terms_of_use.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request :fire:, 준희 👻, QA

#84 [ui] 홈 - 탈퇴 뷰 구현
  app/src/main/java/sopt/motivoo/presentation/MainActivity.kt
  app/src/main/java/sopt/motivoo/presentation/withdrawal/WithdrawalFragment.kt
  app/src/main/res/drawable/ic_unconnection.xml
  app/src/main/res/layout/fragment_mypage_service_out.xml
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
Labels: UI, 준서 👾, QA

#87 [feat] 탈퇴뷰를 탈퇴dialog와 열결
  app/src/main/java/sopt/motivoo/presentation/MyServiceOutFragment.kt
  app/src/main/java/sopt/motivoo/presentation/withdrawal/WithdrawalFragment.kt
  app/src/main/res/layout/fragment_withdrawal.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: feat, Pull Request :fire:, 현지 🐱

#90 [QA] 홈 뷰
  app/src/main/java/sopt/motivoo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/domain/repository/HomeRepository.kt
  app/src/main/java/sopt/motivoo/presentation/MyLogoutFragment.kt
  app/src/main/java/sopt/motivoo/presentation/auth/LoginFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeViewModel.kt
  app/src/main/java/sopt/motivoo/presentation/home/StepCountService.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooMyPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooOtherPieChart.kt
  app/src/main/java/sopt/motivoo/util/custom_view/MotivooStepCountText.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/motivoo_mission_card.xml
  app/src/main/res/layout/motivoo_step_count_text.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request :fire:, 관희 🐪 , QA

#88 [QA] 백그라운드 색상 변경
  app/src/main/java/sopt/motivoo/presentation/onboarding/AgeQuestionFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: Pull Request :fire:, 준희 👻, QA

#92 [feat] 홈 최적화 및 아이콘 생성
  app/src/main/AndroidManifest.xml
  app/src/main/ic_motivoo-playstore.png
  app/src/main/java/sopt/motivoo/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/sopt/motivoo/domain/repository/HomeRepository.kt
  app/src/main/java/sopt/motivoo/presentation/ExerciseFragment.kt
  app/src/main/java/sopt/motivoo/presentation/MyPageFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeConfirmDialogFragment.kt
  app/src/main/java/sopt/motivoo/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/ic_motivoo_background.xml
  app/src/main/res/drawable/ic_motivoo_foreground.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/mipmap-anydpi-v26/ic_motivoo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_motivoo_round.xml
  app/src/main/res/mipmap-hdpi/ic_motivoo.webp
  app/src/main/res/mipmap-hdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-mdpi/ic_motivoo.webp
  app/src/main/res/mipmap-mdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_motivoo.webp
  app/src/main/res/mipmap-xhdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_motivoo.webp
  app/src/main/res/mipmap-xxhdpi/ic_motivoo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_motivoo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_motivoo_round.webp
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request :fire:, 관희 🐪 
